### PR TITLE
Modulesync

### PR DESCRIPTION
**Pull request by rnelson0**
First modulesync version, all code changes related to lint or rubocop failures.
Also replaced nanliu with puppet/voxpupuli in metadata.json and added the full set of badges.

### CODE REVIEW

**Comment by igalic** [comment]
this looks all good, except i thought the plan was to move staging features into archive

**Comment by igalic** [comment]
ping @bmjen ^

**Comment by jyaworski** [comment]
We are slowly migrating to archive. In the meantime, people still use this module.

**Comment by igalic** [comment]
ACK.

**Pull request merged**
