### PR TITLE
Update based on voxpupuli/modulesync_config 0.13.3

### PR DESCRIPTION
**Pull request by dhoppe**
Please merge.

### CODE REVIEW

**Comment by alexjfisher** [comment]
@dhoppe A couple of your modulesync PRs (including this one), seem to have more than the 1 commit I might have been expecting.  Maybe rebase needed to get rid of the superfluous merge commit?

**Comment by dhoppe** [comment]
@alexjfisher Just use the squash and merge option of GitHub and delete the branch. I must have forgotten to rebase between origin and upstream.

**Comment by alexjfisher** [comment]
@dhoppe Done.  Not everybody likes the 'squash and merge' option as it undoes your commit signing.

**Comment by dhoppe** [comment]
@alexjfisher The [commit](https://github.com/voxpupuli/puppet-staging/pull/118/commits) looks fine and rebasing via iPad in front of TV sucks.

**Pull request merged**
