### PR TITLE
Add novalidate option to bypass https validation for powershell

### PR DESCRIPTION
**Pull request by esalberg**
Allows using self-signed certificates to download over https.

### CODE REVIEW

**Comment by esalberg** [comment]
Source:
http://huddledmasses.org/blog/validating-self-signed-certificates-properly-from-powershell/

**Comment by esalberg** [comment]
Not sure about the bundler etc errors - do I need to do anything?

**Comment by bastelfreak** [comment]
Hi @esalberg, sorry for the slow response :(
Are you able to rebase against latest master?

**Comment by ekohl** [comment]
Could you rebase this and see if the tests still fail?

**Comment by esalberg** [comment]
Still showing bundle errors.

**Comment by ekohl** [comment]
The new travis containers broke our workflow. https://github.com/voxpupuli/puppet-staging/commit/e8f4bf7a57f7967ba21f2e65e122aa9e22da89a2 should fix those. Could you do another rebase?

**Comment by bastelfreak** [comment]
I rebased the branch

**Pull request merged**
