### PR TITLE
add support for 7zip

### PR DESCRIPTION
**Pull request by FunFR**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @FunFR, thanks for the PR. Can you please take a look at the used email addr? It isn't associated with your github profile.

**Comment by bastelfreak** [comment]
Hi @FunFR, is it possible that you review the git history? It looks a bit wrong. If you need help with git, feel free to join our IRC channel #voxpupuli on freenode, we are happy to help out.

**Comment by ekohl** [comment]
Could you rebase this? If needed we can help.

**Comment by FunFR** [comment]
done ... Sorry for the delay :)

**Comment by ekohl** [comment]
No problem, sometimes life distracts you. Thanks for rebasing. Could you address the rubocop failure? Then I can merge it and include it in the release I want to make.

**Comment by ekohl** [comment]
Didn't you just add a second commit that fixed rubocop? I don't see it anymore.

**Comment by FunFR** [comment]
squash with rubocop patch

**Comment by ekohl** [comment]
Awesome, thanks!

**Comment by bastelfreak** [comment]
@FunFR please check the used email address in the commit, it isn't associated with your github account.

**Comment by ekohl** [comment]
Merging the tar PR also introduced a merge conflict.

**Comment by ekohl** [comment]
Looks like that didn't work. Did you pull in the latest master?

**Comment by bastelfreak** [comment]
Thanks for the rebase @FunFR !

**Comment by bastelfreak** [comment]
rebased it again

**Pull request merged**
