### PR TITLE
Use ensure_resource to create staging dir. Fixes #109

### LINKED ISSUE #109: Duplicate resource declaration
Hi

I've ran into this issue recently

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/opt/jboss3/.staging/jboss] is already declared in file /etc/puppetlabs/code/environments/jboss_master/modules/staging/manifests/file.pp:39; cannot redeclare at /etc/puppetlabs/code/environments/jboss_master/modules/staging/manifests/file.pp:39

This code has been working for months on end with no issues. 

### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppetserver-2.5.0-1.el7.noarch
- Ruby: 
- Distribution: Centos
- Module version: master

### How to reproduce (e.g Puppet code you use)

  staging::file { "jboss-${::jboss::version}.zip":
    source => "${::jboss::download_url}/jboss-${::jboss::version}.zip",
  } 

### What are you seeing
Duplicate resource declaration

### What behaviour did you expect instead
Create the .staging directory.

### Any additional information you'd like to impart
I've checked the code for file.pp and changed it locally on my side 
from:
`   if ! defined(File[$staging_dir]) {
        file { $staging_dir:
        ensure=>directory,
      }
    }
`
to:
`
ensure_resource('file', $staging_dir, { ensure => directory } )
`

Which fixes the issue. 

Would it be possible to change the above to use ensure_resource which is part of stdlib? 

Thanks
Shaun

### PR DESCRIPTION
**Pull request by shaunrampersad**
Fix for #109

### CODE REVIEW

**Comment by dhoppe** [comment]
@alexjfisher It should not be a problem to use `ensure_resource` instead of `if ! defined( ... )`.

@shaunrampersad Maybe we should also remove `if ! defined( ... )` from `init.pp`.

**Comment by alexjfisher** [comment]
@dhoppe I'd prefer we fix the actual bug rather than papering over it.  ensure_resources will still create duplicate resource errors if the parameters of each resource don't match.
https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/ensure_resource.rb#L18

I think the tests pass because they aren't thorough enough.

**Comment by alexjfisher** [comment]
I've added an extra commit to this PR in https://github.com/voxpupuli/puppet-staging/pull/114
The added test shows a duplicate resource error can still occur.

I haven't got time just right now, but I'll work on the actual fix soon.

**Comment by alexjfisher** [comment]
I've opened https://github.com/voxpupuli/puppet-staging/pull/115

@shaunrampersad If possible, could you let me know if this fixes your issue? (It might not, as your issue seemed to be slightly different from the one I got whilst trying to reproduce).

**Comment by juniorsysadmin** [comment]
@shaunrampersad ping

**Comment by ekohl** [comment]
This module is deprecated in favor of [puppet-archive](https://github.com/voxpupuli/puppet-archive) and as such won't receive any more updates.

**Pull request closed without merging**
