### PR TITLE
Ability to manage file attributes on target

### PR DESCRIPTION
**Pull request by samuelson**
This adds group, user, and mode parameters to the staging::file type to
manage the attributes of the target file.

### CODE REVIEW

**Comment by gioppoluca** [comment]
+1 for this

**Comment by jyaworski** [comment]
Hello:

What's the status of this PR? Can it be squashed?

**Comment by bastelfreak** [comment]
Hi @samuelson, thanks for the PR!
Could you please merge master into the PR? This will fix a bunch of the travis issues.

**Comment by samuelson** [comment]
Sorry @bastelfreak looks like this fell off my radar. I'll try to get it working again.

**Comment by samuelson** [comment]
@bastelfreak this is ready to merge.

**Pull request merged**
