### PR TITLE
"Cleanup unused module and Vagrantfile"

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by jyaworski** [comment]
Would modulesync be better suited here?

**Comment by juniorsysadmin** [comment]
Split this PR

**Comment by jyaworski** [comment]
I think this is contributing to the failures in #78.

**Comment by bastelfreak** [comment]
Hi @nibalizer,

is the PR still needed?

**Comment by juniorsysadmin** [comment]
Superseded by #110

**Pull request closed without merging**
